metadata:
  tipo: playbook
  padre: null
  cx_id: 5ea74bac-7c37-4c8a-bc72-8a4d1cd1868e
  agente: 8d15e440-ab8f-4072-b144-d44919296cd9
displayName: actval_4313cc0c_ciclo_playbook
goal: objetivo de prueba
playbookType: ROUTINE
instruction:
  steps:
  - text: haz algo
